language: java
jdk:
    - oraclejdk8

install: true
sudo: required
script: ./gradlew clean build --stacktrace

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
